# -*- coding: utf-8 -*-
"""HW3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hxu-HMWVZfREPy70YE5LnMM_rM0AQFRd
"""

date = []
for i in range(0,5):
  X = input("数字を入力してください:")
  date.append(int(X))
print("入力データ")
print(date)
print("合計:",sum(date),)