# -*- coding: utf-8 -*-
"""HW4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Dj_W3hgOx0PxbYZ9ziHwKnyP7ShWs7g
"""

while True:
  x  = input("入力：")

  if len(x) ==0:
   print("入力がないので終わります。")
   break

  print("出力："+x)
  print("ちなみに、「"+x+"」の文字列の長さ：",len(x))