# -*- coding: utf-8 -*-
"""HW6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11uVjOy4oEQdbmTldxY9PbOl0qkHih7AQ
"""

import statistics

def Code (A):
  print("最大値:",max(A))
  print("最小値:",min(A))
  print("相加平均:{:.2f}".format(sum(A)/len(A)))
  print("中央値:",statistics.median(A))
  print("不偏標準偏差:{:.4f}".format(statistics.stdev(A)))


date = []
while True:

  D = input("数値:")
  if len(D) == 0:
    break
  date.append(int(D))
print("A:",date)
Code(date)