# -*- coding: utf-8 -*-
"""Final2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18ocQ0a0iFvA2wC2srgKPbaMG75On-ZlD
"""

! wget https://kahoku.news/articles/20210119khn000030.html

import re
from google.colab import files
with open("20210119khn000030.html",'r') as F:
 html = F.read()

html = html.replace("\n","")

html = html.replace("  "," ")

html = html.replace("<br>","")

htmlLines = html.split("</div>")

for l in htmlLines:

   s = re.search('<h1 class="article__title">(.+?)</h1>',l)
   m = re.search('<p class="article__text">(.+?)</p>',l)
   if s:
    Strs = "Title:{0}".format(str(s.group(1)))
   if m:
    Strm = "Discription:{0}".format(str(m.group(1)))

Lines = Strs + "\n" + Strm

with open('sample-kahoku.txt','w') as f:
  f.write(Lines)
  files.download('sample-kahoku.txt')