# -*- coding: utf-8 -*-
"""HW1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1saSwqGozM533erQA49zhLIrIYAsTIjAc
"""

X = input("あなた:")
print("わたし:",X,"の意味は？")

print("ABC", end="\n")
print("abc", end="")