# -*- coding: utf-8 -*-
"""HW12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XjoGrjIqjOncLWRcGDEtDFXIZ9aD8n4s
"""

import matplotlib.pyplot as plt
import numpy as np

plt.rcParams['font.family'] = 'Times New Roman'
x = np.arange(-np.pi,np.pi,0.01)
y = np.cos(x)
plt.xlabel("Angle", fontsize=12)
plt.ylabel("Amplitude", fontsize=12)
plt.xticks([-np.pi, -np.pi/2.0, 0, np.pi/2.0, np.pi],["-π","-π/2","0","π/2","π"])
plt.yticks([-1,-0.75,-0.5,-0.25, 0,0.25,0.5,0.75,1],
["-1.00","-0.75","-0.50","-0.25","0.00","0.25","0.50","0.75","1.00"])
plt.plot(x,y,label="cos")
plt.legend()
plt.show()