# -*- coding: utf-8 -*-
"""HW2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OcQpjj_RqkQ4WY1hRrFyU8lIGbU2O8Kq
"""

X = input("year:")
leap = False
if int(X) % 400 == 0 :
 leap = True
elif int(X) % 100 == 0:
 leap = False
elif  int(X) % 4 == 0:
 leap = True
else:
 leap = False


if leap :
 print("うるう年です")
else:
 print("平年です")

for i in range(1,101):
 print("%03d" % i)