# -*- coding: utf-8 -*-
"""HW7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TbhoNlTn-N6pI8jag8qBcMyaEgHU8UfP
"""

import statistics

from google.colab import files
uploaded = files.upload()

def Code(data2):
 data3 =[]#初期化
 for d in data2:
   d = d.rstrip()#改行の削除
   d = int(d)#整数型へ変換
   data3.append(d)#リストへ追加
 tmp = {}
 oct = []
 tmp["最大値"] = max(data3)
 tmp["最小値"] = min(data3)
 tmp["相加平均"] = statistics.mean(data3)
 tmp["中央値"] = statistics.median(data3)
 tmp["不偏標準偏差"] = "{:.4f}".format(statistics.stdev(data3))
 for k,v in tmp.items():
     print(k,v)
     A = "{0}:{1}".format(str(k),str(v))
     oct.append(A)

 return oct




for fn in uploaded.keys():
 print('アップロードファイル名： "{name}"　　サイズ： {length} bytes'.format(name=fn, length=len(uploaded[fn])))
 with open(fn,"r") as F:
   data = F.readlines()
 newData = Code(data)
 NewFn = "New_" + fn
 with open(NewFn,"w") as newF:
    for l in newData:
     newF.write(l+"\n")
 files.download(newFn)